# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Optional introduction shown above the list of readings.')),
                ('faq', wagtail.fields.StreamField([('faq', 5)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'help_text': 'The heading shown above this list of questions.', 'max_length': 100}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'The question, written the way a visitor would ask it.', 'max_length': 200}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Your answer. Keep it plain and reassuring.'}), 3: ('wagtail.blocks.StructBlock', [[('question', 1), ('answer', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {}), 5: ('wagtail.blocks.StructBlock', [[('heading', 0), ('questions', 4)]], {})}, help_text='Optional FAQ section shown below the list of readings (§7 includes FAQ as content that supports bookings).')),
            ],
            options={
                'verbose_name': 'Services page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Reading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The name of this reading as visitors will see it, e.g. 'Natal Chart Reading'.", max_length=100)),
                ('tag_label', models.CharField(blank=True, help_text="A short category tag shown next to this reading's number on the Services and Readings pages, e.g. 'Natal chart' or 'Year ahead'. Leave blank to show just the number.", max_length=40)),
                ('summary', models.CharField(help_text='A one- or two-sentence description shown on cards on the homepage and Services page.', max_length=220)),
                ('description', models.TextField(blank=True, help_text="A longer description for this reading's own page. Leave blank to show just the summary above.")),
                ('features', wagtail.fields.StreamField([('item', 0)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Feature', 'max_length': 150})}, help_text="Short bullet points describing what's included, e.g. '60 minutes, online or by phone' or 'Recording sent afterwards'. Shown as a checklist on this reading's own page.")),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text='How long this reading usually takes, in minutes. Leave blank if it varies.', null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Price in NZD. Leave blank until pricing is confirmed — the note below will be shown instead of a number.', max_digits=8, null=True)),
                ('price_note', models.CharField(blank=True, default='Price on enquiry', help_text="Shown instead of, or alongside, the price — e.g. 'From $150' or 'Price on enquiry'. Leave as-is until pricing is confirmed.", max_length=60)),
                ('is_active', models.BooleanField(default=True, help_text="Untick to hide this reading from the site without deleting it (e.g. while it's temporarily unavailable).")),
                ('is_most_booked', models.BooleanField(default=False, help_text="Tick to show a 'Most booked' highlight on this reading's card. Only tick this for one reading at a time.")),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the order readings are listed in. Lower numbers show first.')),
                ('image', models.ForeignKey(blank=True, help_text='Optional image or icon representing this reading.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Reading',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ReadingDetailPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 3), ('faq', 9)], blank=True, block_lookup={0: ('apps.core.blocks.BodyTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image from the image library.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional line of text shown under the image, e.g. a photo credit.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'default': 'Frequently Asked Questions', 'help_text': 'The heading shown above this list of questions.', 'max_length': 100}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': 'The question, written the way a visitor would ask it.', 'max_length': 200}), 6: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Your answer. Keep it plain and reassuring.'}), 7: ('wagtail.blocks.StructBlock', [[('question', 5), ('answer', 6)]], {}), 8: ('wagtail.blocks.ListBlock', (7,), {}), 9: ('wagtail.blocks.StructBlock', [[('heading', 4), ('questions', 8)]], {})}, help_text='Extra detail for this reading beyond its short summary — what to expect, how to prepare, or a short FAQ.')),
                ('reading', models.OneToOneField(help_text='Which reading this page is about. Set the reading up in Snippets → Readings first, then choose it here.', on_delete=django.db.models.deletion.PROTECT, related_name='detail_page', to='readings.reading')),
            ],
            options={
                'verbose_name': 'Reading detail page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
