# Generated by Django 5.1.15 on 2026-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reading',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank until pricing is confirmed — the note below will be shown instead of a number.', max_digits=8, null=True),
        ),
    ]
