# Generated by Django 5.1.15 on 2026-09-25 13:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('readings', '0002_alter_reading_price_help_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readingdetailpage',
            name='body',
            field=wagtail.fields.StreamField([('text', 0), ('image', 3)], blank=True, block_lookup={0: ('apps.core.blocks.BodyTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image from the image library.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional line of text shown under the image, e.g. a photo credit.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {})}, help_text='Extra detail for this reading beyond its short summary — what to expect or how to prepare.'),
        ),
    ]
