# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Shown above the contact form.')),
                ('thank_you_message', models.TextField(blank=True, default="Thank you — your message has been sent. I'll be in touch soon.", help_text='Shown after someone successfully submits the contact form.')),
            ],
            options={
                'verbose_name': 'Contact page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('message', models.TextField()),
                ('newsletter_opt_in', models.BooleanField(default=False, help_text='Whether this person also asked to join the newsletter.')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact submission',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('source', models.CharField(blank=True, help_text="Where this signup came from, e.g. 'homepage footer' or 'contact page'. Helps Leslie see what's working.", max_length=50)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Newsletter signup',
                'ordering': ['-subscribed_at'],
            },
        ),
    ]
