# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('google_analytics_id', models.CharField(blank=True, default='', help_text="Your Google Analytics measurement ID (looks like 'G-XXXXXXXXXX'). Leave blank to disable analytics tracking.", max_length=20)),
            ],
            options={
                'verbose_name': 'Analytics',
            },
        ),
        migrations.CreateModel(
            name='ContactSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(blank=True, default='', help_text='The email address clients should use to reach you, and the one the contact form and booking notifications will use. Nothing will be shown on the site until this is filled in.', max_length=254)),
                ('contact_phone', models.CharField(blank=True, default='', help_text="Optional phone number shown on the Contact page. Leave blank if you'd rather clients only reach you by email or the booking form.", max_length=30)),
                ('studio_address', models.CharField(blank=True, default='', help_text='Optional. Only fill this in if you see clients in person and want the address shown on the Contact page.', max_length=255)),
                ('instagram_url', models.URLField(blank=True, default='', help_text='Full web address of your Instagram profile, if you have one.')),
                ('facebook_url', models.URLField(blank=True, default='', help_text='Full web address of your Facebook page, if you have one.')),
                ('years_experience_label', models.CharField(default='Experience details coming soon', help_text="How your experience is described around the site, e.g. '12+ years'. Shown on the homepage and About page. Update this once here and it changes everywhere.", max_length=60)),
            ],
            options={
                'verbose_name': 'Contact details',
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField(help_text="The testimonial itself, in the client's own words. Keep identifying details out unless the client is happy to be named.")),
                ('author_name', models.CharField(help_text="Who this is from, e.g. 'Sarah M.' First name and last initial is usually enough to feel genuine while protecting privacy.", max_length=100)),
                ('author_descriptor', models.CharField(blank=True, help_text="Optional short context under the name, e.g. 'Natal Chart Reading' or 'Auckland'.", max_length=150)),
                ('is_featured', models.BooleanField(default=False, help_text='Tick to make this testimonial available to pick for the homepage. Untick to keep it on file without showing it anywhere.')),
            ],
            options={
                'verbose_name': 'Testimonial',
                'ordering': ['-is_featured', 'author_name'],
            },
        ),
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='A short introduction shown near the top of the page, above your full story.')),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 3)], blank=True, block_lookup={0: ('apps.core.blocks.BodyTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image from the image library.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional line of text shown under the image, e.g. a photo credit.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {})}, help_text='Your story and philosophy. Add as many text and image sections as you like, in whatever order reads best.')),
                ('pull_quote', models.CharField(blank=True, help_text='A short line pulled out and shown in large italic type, e.g. your guiding philosophy in one sentence.', max_length=300)),
                ('three_promises', wagtail.fields.StreamField([('section', 6)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'What you can expect', 'help_text': 'Small label shown above the heading.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Three promises', 'max_length': 100}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "A short promise, e.g. 'No judgement'.", 'max_length': 60}), 3: ('wagtail.blocks.TextBlock', (), {'help_text': 'One or two sentences explaining what this promise means for a client.', 'max_length': 250}), 4: ('wagtail.blocks.StructBlock', [[('title', 2), ('description', 3)]], {}), 5: ('wagtail.blocks.ListBlock', (4,), {'help_text': 'Exactly three promises, in the order they should appear.', 'max_num': 3, 'min_num': 3}), 6: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('promises', 5)]], {})}, help_text="The 'Three promises' section showing what a client can expect from working with you.")),
                ('training_background', wagtail.fields.StreamField([('section', 7)], block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Training & background', 'help_text': 'Small label shown above the heading.', 'max_length': 60}), 1: ('wagtail.blocks.CharBlock', (), {'default': 'Where the knowledge comes from', 'help_text': 'Heading for this section.', 'max_length': 100}), 2: ('wagtail.blocks.RichTextBlock', (), {'features': ['bold', 'italic', 'link', 'ol', 'ul'], 'help_text': 'Your training, qualifications and background as an astrologer.'}), 3: ('wagtail.blocks.CharBlock', (), {'default': 'Book a Reading', 'help_text': "The words on the button, e.g. 'Book a Reading'. Keep it short so it fits on one line.", 'max_length': 40}), 4: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Choose a page on this site for the button to open. Use this instead of the web address below whenever you can — it keeps working even if the page's URL changes.", 'required': False}), 5: ('wagtail.blocks.URLBlock', (), {'help_text': 'Only fill this in if the button should go somewhere outside this site (e.g. an external booking tool). Leave blank if you chose a page above.', 'label': 'Or a web address', 'required': False}), 6: ('wagtail.blocks.StructBlock', [[('text', 3), ('page', 4), ('url', 5)]], {'help_text': 'Optional link at the end of this section, e.g. through to the Readings page.', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('eyebrow', 0), ('heading', 1), ('body', 2), ('link', 6)]], {})}, help_text="The 'Training & background' section — your qualifications and study.")),
                ('cta', wagtail.fields.StreamField([('button', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'default': 'Book a Reading', 'help_text': "The words on the button, e.g. 'Book a Reading'. Keep it short so it fits on one line.", 'max_length': 40}), 1: ('wagtail.blocks.PageChooserBlock', (), {'help_text': "Choose a page on this site for the button to open. Use this instead of the web address below whenever you can — it keeps working even if the page's URL changes.", 'required': False}), 2: ('wagtail.blocks.URLBlock', (), {'help_text': 'Only fill this in if the button should go somewhere outside this site (e.g. an external booking tool). Leave blank if you chose a page above.', 'label': 'Or a web address', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('text', 0), ('page', 1), ('url', 2)]], {})}, help_text='An optional button at the end of the page, e.g. inviting visitors to book a reading.')),
                ('portrait', models.ForeignKey(blank=True, help_text='Your portrait photo. A vertical black-and-white photo works best with this design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'About page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
