# Generated by Django 5.1.15 on 2026-09-24 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='author_descriptor',
            field=models.CharField(blank=True, help_text="Optional short context under the name, e.g. 'Natal Chart Reading' or 'Austin, TX'.", max_length=150),
        ),
    ]
