# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The category name as visitors will see it, e.g. 'Transits'.", max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, help_text="Used in the category filter's web address. Leave blank to generate this automatically from the name.", max_length=60, unique=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls the order categories appear in the filter bar. Lower numbers show first.')),
            ],
            options={
                'verbose_name': 'Blog category',
                'verbose_name_plural': 'Blog categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BlogIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Optional introduction shown above the list of posts.')),
            ],
            options={
                'verbose_name': 'Blog index page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('published_date', models.DateTimeField(help_text='When this post should appear as published. Backdate this for posts migrated from the old Blogger blog so they keep their original date.')),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown on the blog index and homepage. Leave blank to use the start of the post instead.', max_length=300)),
                ('body', wagtail.fields.StreamField([('text', 0), ('image', 3)], block_lookup={0: ('apps.core.blocks.BodyTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Choose an image from the image library.'}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Optional line of text shown under the image, e.g. a photo credit.', 'max_length': 200, 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('image', 1), ('caption', 2)]], {})}, help_text='The post itself. Add as many text and image sections as you like, in whatever order reads best.')),
                ('author_name', models.CharField(default='Leslie Hale', help_text="Shown as this post's author. Change only for a guest post.", max_length=100)),
                ('source_url', models.URLField(blank=True, help_text='If this post was migrated from the old Blogger blog, paste its original address here so old links can be redirected to this page.')),
                ('category', models.ForeignKey(blank=True, help_text="Which category this post belongs to — shown as its tag and used by the blog's category filter. Set the category up first in Snippets → Blog categories, then choose it here.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.blogcategory')),
                ('featured_image', models.ForeignKey(blank=True, help_text='Image shown with this post on the blog index and homepage.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Blog post',
            },
            bases=('wagtailcore.page',),
        ),
    ]
