# Generated by Django 5.1.4 on 2026-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='blogger_content_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Internal checksum of the content last written by the Blogger importer, used to detect whether a post changed upstream since the last import run. Not shown in the editor.', max_length=64),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blogger_post_id',
            field=models.CharField(blank=True, db_index=True, help_text='Set automatically by the Blogger importer (blog-migration). The stable ID of this post in the old Blogger export, used to match it on re-import so re-running the import updates this post instead of creating a duplicate. Leave blank for posts written directly in Wagtail — it is never required for a normal post.', max_length=100, null=True, unique=True),
        ),
    ]
