# Generated by Django 5.1.15 on 2026-09-23 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpost_blogger_content_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='keen_content_hash',
            field=models.CharField(blank=True, default='', editable=False, help_text='Internal checksum of the content last written by the Keen archive importer, used to detect whether a re-run needs to update this post. Not shown in the editor.', max_length=64),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='keen_post_id',
            field=models.CharField(blank=True, db_index=True, help_text="Set automatically by the Keen archive importer (blog-migration). The numeric post ID from this post's original keen.com URL, used to match it on re-import so re-running the import updates this post instead of creating a duplicate. Leave blank for posts written directly in Wagtail.", max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='original_category_label',
            field=models.TextField(blank=True, default='', help_text="The original 'Filed Under' label text from the Keen archive, preserved exactly as written. This post's own 'Category' field above is a single curated bucket chosen from these labels for the site's filter bar — this field keeps the full original text so nothing from the source archive is lost."),
        ),
    ]
