# Generated by Django 5.1.15 on 2026-09-23 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_seed_keen_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='source_url',
            field=models.URLField(blank=True, help_text='If this post was migrated from the old Blogger blog or the old Keen.com blog, paste its original address here so old links can be redirected to this page.', max_length=500),
        ),
    ]
