# Generated by Django 5.1.15 on 2026-09-25 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogpost_source_url'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeenImportedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_filename', models.CharField(help_text="The exact filename this image had in the Keen archive's images/ directory (e.g. 'ff89d795bce6c539.jpg') — never the filename actually stored in Wagtail, which can differ (a corrected extension, or a rename Wagtail applies to avoid a storage-name collision).", max_length=255, unique=True)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'verbose_name': 'Keen imported image',
                'verbose_name_plural': 'Keen imported images',
            },
        ),
    ]
