# Generated by Django 5.1.15 on 2026-09-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BackofficeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': [('access_backoffice', 'Can access the management dashboard (/manage/)')],
                'managed': False,
                'default_permissions': (),
            },
        ),
    ]
