"""
Production settings.

DEBUG is hard-coded False here, deliberately not sourced from the
environment, so a missing or mistyped env var can never re-enable it.

ALLOWED_HOSTS / CSRF_TRUSTED_ORIGINS have NO hardcoded domain default, on
purpose. This settings module is used for both the leslie.testground.shop
test deployment and, later, the real lesliehale-astrology.com cutover
(PROJECT-SCOPE.md §1) — a default baked in here would be silently wrong
for whichever of those two is NOT the current deploy. Same reasoning as
SECRET_KEY: a required value that fails loudly beats a default that fails
quietly. Both are required from the environment; see .env.example.
"""

from .base import env, env_bool, env_list  # noqa: F401
from .base import *  # noqa: F401,F403

DEBUG = False

# Required, no default — set to the real host(s) for whichever deploy this
# is (currently "leslie.testground.shop"; "lesliehale-astrology.com,
# www.lesliehale-astrology.com" at cutover). Comma-separated.
ALLOWED_HOSTS = env_list("DJANGO_ALLOWED_HOSTS", required=True)

# Required, no default — same reasoning, and must include the scheme
# (e.g. "https://leslie.testground.shop"). Comma-separated.
CSRF_TRUSTED_ORIGINS = env_list("CSRF_TRUSTED_ORIGINS", required=True)

# --- Email: SMTP, credentials required in prod (no blank fallback here) ---
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")  # noqa: F405
EMAIL_HOST_USER = env("EMAIL_HOST_USER")  # noqa: F405
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")  # noqa: F405
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")  # noqa: F405

# --- HTTPS / cookie / header hardening ---
# ASSUMPTION (needs Prohosting confirmation): the edge that terminates TLS
# sits in front of this container and forwards X-Forwarded-Proto. If
# Prohosting terminates TLS itself and does NOT set that header, this must
# change or SECURE_SSL_REDIRECT will loop.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = True
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True

# --- HSTS: configurable, safe-by-default for a throwaway test domain -----
# SECURE_HSTS_PRELOAD is effectively irreversible once a browser vendor's
# preload list actually picks up leslie.testground.shop — removal takes
# months — and a year-long SECURE_HSTS_SECONDS on a host that might later
# be reused for something served over plain HTTP means every browser that
# ever visited refuses to connect until the max-age it cached expires.
# Neither is a safe default for a test deployment, so both now come from
# the environment rather than being hard-coded on:
#
#   SECURE_HSTS_SECONDS defaults to 0 — Django's SecurityMiddleware omits
#   the Strict-Transport-Security header entirely at 0, i.e. HSTS is OFF
#   by default here. That is the correct default for
#   leslie.testground.shop today.
#
#   SECURE_HSTS_INCLUDE_SUBDOMAINS and SECURE_HSTS_PRELOAD default to
#   False and are meaningless while SECURE_HSTS_SECONDS is 0 in any case.
#
# At the real lesliehale-astrology.com cutover (PROJECT-SCOPE.md §1), set
# in the environment — do not edit this file:
#   SECURE_HSTS_SECONDS=31536000
#   SECURE_HSTS_INCLUDE_SUBDOMAINS=true
#   SECURE_HSTS_PRELOAD=true
# and only after confirming TLS is stable on the real domain. Ramp up
# gradually if in doubt (e.g. a short max-age like 300 or 86400 for a few
# days first) rather than jumping straight to a year — an HSTS mistake at
# a short max-age expires on its own; a year-long one does not. Actual
# inclusion in browsers' preload lists is a separate, manual submission at
# https://hstspreload.org once SECURE_HSTS_PRELOAD=true has been live and
# verified — setting the Django flag alone does not submit anything.
SECURE_HSTS_SECONDS = int(env("SECURE_HSTS_SECONDS", required=False, default="0"))  # noqa: F405
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_bool(  # noqa: F405
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", required=False, default="False"
)
SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", required=False, default="False")  # noqa: F405

SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "same-origin"
X_FRAME_OPTIONS = "DENY"

# WAGTAILADMIN_BASE_URL must be the real HTTPS domain in prod; base.py
# already requires it from the environment, so nothing extra to set here.
