# Generated by Django 5.1.4 on 2026-09-22 10:19
#
# Hand-edited after generation: added BtreeGistExtension (required by
# Postgres before an ExclusionConstraint using a gist index can be
# created — see the AddConstraint for 'booking_no_overlapping_active_slots'
# below, which is the database-level guard against double-booking that
# CLAUDE.md's correctness rules require). Django's autodetector does not
# add this operation on its own.

import django.contrib.postgres.constraints
import django.db.models.deletion
import uuid
from django.contrib.postgres.operations import BtreeGistExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('readings', '0001_initial'),
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        BtreeGistExtension(),
        migrations.CreateModel(
            name='AvailabilityException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('is_closed', models.BooleanField(default=True, help_text='Tick to block this date entirely. Untick to set special one-off hours below instead of your usual weekly availability.')),
                ('start_time', models.TimeField(blank=True, help_text="Only used when 'Closed all day' is unticked.", null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, help_text="Optional private note for your own reference, e.g. 'Public holiday'.", max_length=120)),
            ],
            options={
                'verbose_name': 'Availability exception',
                'verbose_name_plural': 'Availability exceptions',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], help_text='Which day of the week this window applies to, every week.')),
                ('start_time', models.TimeField(help_text='When you become available that day, in your own local time.')),
                ('end_time', models.TimeField(help_text='When you stop being available that day. Must be after the start time.')),
                ('is_active', models.BooleanField(default=True, help_text='Untick to switch off this window without deleting it.')),
            ],
            options={
                'verbose_name': 'Availability rule',
                'verbose_name_plural': 'Availability rules',
                'ordering': ['weekday', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BookingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Shown above the booking calendar, e.g. how the process works.')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Your cancellation/rescheduling policy, shown near the booking form and included in confirmation emails.')),
                ('confirmation_message', models.TextField(blank=True, help_text='Shown to a client immediately after they submit a booking request, before payment or confirmation is complete.')),
            ],
            options={
                'verbose_name': 'Booking page',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_ref', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('client_first_name', models.CharField(max_length=80)),
                ('client_last_name', models.CharField(max_length=80)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, help_text="Client's date of birth.", null=True)),
                ('birth_time', models.TimeField(blank=True, help_text="Client's time of birth, if known.", null=True)),
                ('birth_time_unknown', models.BooleanField(default=False, help_text="Client told us they don't know their exact birth time.")),
                ('birth_place', models.CharField(blank=True, help_text='City/country of birth, as given by the client.', max_length=150)),
                ('client_notes', models.TextField(blank=True, help_text="What the client said they'd like to focus on (optional, client-provided free text).")),
                ('start_at', models.DateTimeField(help_text='Appointment start, stored in UTC.')),
                ('end_at', models.DateTimeField(help_text='Appointment end, stored in UTC.')),
                ('duration_minutes', models.PositiveIntegerField(help_text="Snapshot of the reading's duration at the time of booking, so a later change to the reading's typical duration never rewrites what was actually booked.")),
                ('display_timezone', models.CharField(help_text="The IANA timezone name shown to the client when they chose this slot (e.g. 'Pacific/Auckland'), so confirmation emails describe the same time the client actually saw and clicked, not a re-derived one.", max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending — held, awaiting payment'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('hold_expires_at', models.DateTimeField(blank=True, help_text="While status is 'pending', when this hold releases the slot back to availability if payment hasn't completed by then.", null=True)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded'), ('not_required', 'Not required')], default='unpaid', max_length=20)),
                ('payment_provider', models.CharField(blank=True, help_text="Which payment tool processed this booking, e.g. 'stripe'. Set by whichever adapter in apps/bookings/payments/ handled it.", max_length=30)),
                ('payment_reference', models.CharField(blank=True, help_text="The payment provider's own reference for this booking (e.g. a Stripe Checkout Session ID) — how incoming webhooks are matched back to this row.", max_length=120, null=True, unique=True)),
                ('amount_minor', models.PositiveIntegerField(default=0, help_text="The amount charged, in integer minor currency units (e.g. cents) — never a float. Snapshot of the reading's price at the time of booking.")),
                ('currency', models.CharField(default='NZD', max_length=3)),
                ('confirmation_email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_email_error', models.CharField(blank=True, help_text='Set automatically if the confirmation email failed to send (exception type only — never message content that could carry personal data). Cleared once a resend succeeds.', max_length=200)),
                ('internal_notes', models.TextField(blank=True, help_text='Private notes for Leslie only — never shown to the client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reading', models.ForeignKey(help_text='Which reading this booking is for.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='readings.reading')),
            ],
            options={
                'verbose_name': 'Booking',
                'ordering': ['-start_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=30)),
                ('event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(max_length=60)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('booking', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_events', to='bookings.booking')),
            ],
            options={
                'verbose_name': 'Payment event',
            },
        ),
        migrations.AddConstraint(
            model_name='booking',
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(condition=models.Q(('status__in', ['pending', 'confirmed', 'completed'])), expressions=[(models.Func('start_at', 'end_at', function='tstzrange'), '&&')], name='booking_no_overlapping_active_slots'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'event_id'), name='unique_provider_event'),
        ),
    ]
