# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0094_alter_page_locale'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(blank=True, max_length=30)),
                ('requested_start', models.DateTimeField(help_text="The date and time requested, in the site's local time zone.")),
                ('duration_minutes', models.PositiveIntegerField(blank=True, help_text="Snapshot of the reading's duration at the time of booking.", null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('payment_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('not_required', 'Not required')], default='unpaid', max_length=20)),
                ('payment_provider', models.CharField(blank=True, help_text='Which payment tool processed this booking (e.g. Stripe, PayPal). Left blank until the payment integration is confirmed and wired up.', max_length=30)),
                ('payment_reference', models.CharField(blank=True, help_text="The payment processor's own reference/transaction ID, once payment has been taken.", max_length=120)),
                ('client_notes', models.TextField(blank=True, help_text='Anything the client added when requesting this booking.')),
                ('internal_notes', models.TextField(blank=True, help_text='Private notes for Leslie only — never shown to the client.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'ordering': ['-requested_start'],
            },
        ),
        migrations.CreateModel(
            name='BookingPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('intro', models.TextField(blank=True, help_text='Shown above the booking calendar, e.g. how the process works.')),
                ('cancellation_policy', models.TextField(blank=True, help_text='Your cancellation/rescheduling policy, shown near the booking form.')),
                ('confirmation_message', models.TextField(blank=True, help_text='Shown to a client immediately after they submit a booking request, before payment or confirmation is complete.')),
            ],
            options={
                'verbose_name': 'Booking page',
            },
            bases=('wagtailcore.page',),
        ),
    ]
