# Generated by Django 5.1.4 on 2026-09-22 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('readings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reading',
            field=models.ForeignKey(help_text='Which reading this booking is for.', on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='readings.reading'),
        ),
    ]
