# Generated by Django 5.1.15 on 2026-09-24 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='booking',
            name='display_timezone',
            field=models.CharField(help_text="The IANA timezone name shown to the client when they chose this slot (e.g. 'America/New_York'), so confirmation emails describe the same time the client actually saw and clicked, not a re-derived one.", max_length=64),
        ),
    ]
